version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: production
      - dependency-type: development
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
