import type { Locale } from '../i18n';
import type { BuiltInPreset, BuiltInSound, ParticleCurve, ParticleRelease } from '../../../src/snapdom';
import type { RangeDefinition } from './playground-state';

export const copies = {
  en: {
    presetTitle: 'Ready-made effects',
    readyEffects: 'Ready-made effects',
    curve: 'Curve',
    release: 'Direction',
    preview: 'Preview',
    cardShape: 'Card shape',
    cardShapeUpright: 'Upright card',
    cardShapeWide: 'Wide card',
    cardHint: 'Click "Remove/Restore" to see the effect',
    codeTab: 'Ready code',
    remove: 'Remove',
    restore: 'Restore',
    removeMode: 'Removal',
    restoreMode: 'Restoration',
    operation: 'Animation',
    reset: 'Reset',
    undo: 'Undo',
    settingsLabel: 'Parameter groups',
    timing: 'Timing',
    horizontal: 'Horizontal',
    vertical: 'Vertical',
    particles: 'Particles',
    sound: 'Sound',
    soundEnabled: 'Enable sound',
    soundSource: 'Sound source',
    soundReverse: 'Reverse',
    customSound: 'Custom file',
    chooseSound: 'Choose file',
    changeSound: 'Replace',
    removeSound: 'Remove',
    localSoundNote: 'Stored in the browser IndexedDB.',
    bundledSoundNote: 'Bundled with the package.',
    audioTooLarge: 'Choose a file no larger than 5 MB.',
    audioTooLong: 'Choose audio no longer than 10 seconds.',
    audioInvalid: 'The browser could not read this audio file.',
    audioSaving: 'Saving audio locally…',
    soundVolume: 'Volume',
    soundPlaybackRate: 'Speed',
    soundDelay: 'Delay',
    soundFadeDuration: 'Fade',
    on: 'On',
    off: 'Off',
    copyEffect: 'Copy code',
    copyEffectShort: 'Copy code',
    copyLink: 'Copy effect link',
    copyLinkShort: 'Copy link',
    copied: 'Copied',
    copyFailed: 'Clipboard is unavailable',
    ready: 'Ready',
    preparing: 'Preparing snapshot…',
    updated: 'Configuration updated',
    duration: 'Duration',
    stagger: 'Stagger',
    horizontalDrift: 'Drift',
    horizontalMin: 'Minimum',
    horizontalMax: 'Maximum',
    verticalMin: 'Minimum',
    verticalMax: 'Maximum',
    convergence: 'Center pull',
    swirl: 'Swirl',
    waveTurns: 'Wave turns',
    endScale: 'End scale',
    particleSize: 'Particle size',
    alphaThreshold: 'Alpha threshold',
    releaseRandomness: 'Release randomness',
    fadeStart: 'Fade start',
    layoutRelease: 'Layout handoff',
    rotationMin: 'Minimum rotation',
    rotationMax: 'Maximum rotation',
  },
  ru: {
    presetTitle: 'Готовые эффекты',
    readyEffects: 'Готовые эффекты',
    curve: 'Кривая',
    release: 'Направление',
    preview: 'Предпросмотр',
    cardShape: 'Форма карточки',
    cardShapeUpright: 'Вертикальная карточка',
    cardShapeWide: 'Горизонтальная карточка',
    cardHint: 'Нажмите "Удалить/Восстановить", чтобы увидеть эффект',
    codeTab: 'Готовый код',
    remove: 'Удалить',
    restore: 'Восстановить',
    removeMode: 'Удаление',
    restoreMode: 'Восстановление',
    operation: 'Анимация',
    reset: 'Сбросить',
    undo: 'Вернуть',
    settingsLabel: 'Группы параметров',
    timing: 'Тайминг',
    horizontal: 'Горизонталь',
    vertical: 'Вертикаль',
    particles: 'Частицы',
    sound: 'Звук',
    soundEnabled: 'Включить звук',
    soundSource: 'Источник звука',
    soundReverse: 'Реверс',
    customSound: 'Свой файл',
    chooseSound: 'Выбрать файл',
    changeSound: 'Заменить',
    removeSound: 'Удалить',
    localSoundNote: 'Хранится в IndexedDB браузера.',
    bundledSoundNote: 'Встроенный звук из пакета.',
    audioTooLarge: 'Выберите файл размером не больше 5 МБ.',
    audioTooLong: 'Выберите звук длительностью не больше 10 секунд.',
    audioInvalid: 'Браузер не смог прочитать этот аудиофайл.',
    audioSaving: 'Сохраняем звук в браузере…',
    soundVolume: 'Громкость',
    soundPlaybackRate: 'Скорость',
    soundDelay: 'Задержка',
    soundFadeDuration: 'Фейд',
    on: 'Вкл.',
    off: 'Выкл.',
    copyEffect: 'Копировать код',
    copyEffectShort: 'Копировать код',
    copyLink: 'Скопировать ссылку на эффект',
    copyLinkShort: 'Копировать ссылку',
    copied: 'Скопировано',
    copyFailed: 'Буфер обмена недоступен',
    ready: 'Готово',
    preparing: 'Подготавливаем снимок…',
    updated: 'Настройки обновлены',
    duration: 'Длительность',
    stagger: 'Разброс старта',
    horizontalDrift: 'Разброс',
    horizontalMin: 'Минимум',
    horizontalMax: 'Максимум',
    verticalMin: 'Минимум',
    verticalMax: 'Максимум',
    convergence: 'К центру',
    swirl: 'Колебание',
    waveTurns: 'Число колебаний',
    endScale: 'Размер в конце',
    particleSize: 'Размер частиц',
    alphaThreshold: 'Порог прозрачности',
    releaseRandomness: 'Случайность распада',
    fadeStart: 'Начало затухания',
    layoutRelease: 'Изменение раскладки',
    rotationMin: 'Минимальный поворот',
    rotationMax: 'Максимальный поворот',
  },
  zh: {
    presetTitle: '现成效果',
    readyEffects: '现成效果',
    curve: '曲线',
    release: '方向',
    preview: '预览',
    cardShape: '卡片形状',
    cardShapeUpright: '竖版卡片',
    cardShapeWide: '横版卡片',
    cardHint: '点击"删除/恢复"查看效果',
    codeTab: '可用代码',
    remove: '删除',
    restore: '恢复',
    removeMode: '删除',
    restoreMode: '恢复',
    operation: '动画',
    reset: '重置',
    undo: '撤销',
    settingsLabel: '参数组',
    timing: '时间',
    horizontal: '水平',
    vertical: '垂直',
    particles: '粒子',
    sound: '声音',
    soundEnabled: '开启声音',
    soundSource: '声音来源',
    soundReverse: '反向',
    customSound: '自定义文件',
    chooseSound: '选择文件',
    changeSound: '替换',
    removeSound: '删除',
    localSoundNote: '保存在浏览器的 IndexedDB 中。',
    bundledSoundNote: '随包提供的内置音频。',
    audioTooLarge: '请选择不超过 5 MB 的文件。',
    audioTooLong: '请选择不超过 10 秒的音频。',
    audioInvalid: '浏览器无法读取此音频文件。',
    audioSaving: '正在本地保存音频…',
    soundVolume: '音量',
    soundPlaybackRate: '速度',
    soundDelay: '延迟',
    soundFadeDuration: '淡入淡出',
    on: '开',
    off: '关',
    copyEffect: '复制代码',
    copyEffectShort: '复制代码',
    copyLink: '复制效果链接',
    copyLinkShort: '复制链接',
    copied: '已复制',
    copyFailed: '剪贴板不可用',
    ready: '就绪',
    preparing: '正在准备快照…',
    updated: '配置已更新',
    duration: '持续时间',
    stagger: '启动延迟',
    horizontalDrift: '漂移',
    horizontalMin: '最小值',
    horizontalMax: '最大值',
    verticalMin: '最小值',
    verticalMax: '最大值',
    convergence: '向中心',
    swirl: '摆动',
    waveTurns: '波动次数',
    endScale: '结束缩放',
    particleSize: '粒子大小',
    alphaThreshold: 'Alpha 阈值',
    releaseRandomness: '释放随机度',
    fadeStart: '淡出起点',
    layoutRelease: '布局切换',
    rotationMin: '最小旋转',
    rotationMax: '最大旋转',
  },
  ko: {
    presetTitle: '준비된 효과',
    readyEffects: '준비된 효과',
    curve: '곡선',
    release: '방향',
    preview: '미리보기',
    cardShape: '카드 형태',
    cardShapeUpright: '세로형 카드',
    cardShapeWide: '가로형 카드',
    cardHint: '"삭제/복원"을 눌러 효과를 확인하세요',
    codeTab: '사용 가능한 코드',
    remove: '삭제',
    restore: '복원',
    removeMode: '삭제',
    restoreMode: '복원',
    operation: '애니메이션',
    reset: '초기화',
    undo: '되돌리기',
    settingsLabel: '매개변수 그룹',
    timing: '타이밍',
    horizontal: '가로',
    vertical: '세로',
    particles: '파티클',
    sound: '사운드',
    soundEnabled: '사운드 켜기',
    soundSource: '사운드 소스',
    soundReverse: '역재생',
    customSound: '사용자 파일',
    chooseSound: '파일 선택',
    changeSound: '교체',
    removeSound: '삭제',
    localSoundNote: '브라우저 IndexedDB에 저장됩니다.',
    bundledSoundNote: '패키지에 포함된 사운드입니다.',
    audioTooLarge: '5 MB 이하의 파일을 선택하세요.',
    audioTooLong: '10초 이하의 오디오를 선택하세요.',
    audioInvalid: '브라우저에서 이 오디오 파일을 읽을 수 없습니다.',
    audioSaving: '브라우저에 오디오 저장 중…',
    soundVolume: '볼륨',
    soundPlaybackRate: '속도',
    soundDelay: '지연',
    soundFadeDuration: '페이드',
    on: '켜짐',
    off: '꺼짐',
    copyEffect: '코드 복사',
    copyEffectShort: '코드 복사',
    copyLink: '효과 링크 복사',
    copyLinkShort: '링크 복사',
    copied: '복사됨',
    copyFailed: '클립보드를 사용할 수 없음',
    ready: '준비됨',
    preparing: '스냅샷 준비 중…',
    updated: '설정이 업데이트됨',
    duration: '재생 시간',
    stagger: '시작 지연',
    horizontalDrift: '분산',
    horizontalMin: '최솟값',
    horizontalMax: '최댓값',
    verticalMin: '최솟값',
    verticalMax: '최댓값',
    convergence: '중앙으로',
    swirl: '흔들림',
    waveTurns: '진동 횟수',
    endScale: '최종 크기',
    particleSize: '파티클 크기',
    alphaThreshold: '알파 임곗값',
    releaseRandomness: '방출 무작위성',
    fadeStart: '페이드 시작',
    layoutRelease: '레이아웃 전환',
    rotationMin: '최소 회전',
    rotationMax: '최대 회전',
  },
} as const;

export const helps = {
  en: {
    curve: 'Changes how particles accelerate and fade without changing where they travel.',
    release: 'Determines which part of the element starts disintegrating first.',
    particleSize: 'Minimum particle edge in CSS pixels. Zero keeps adaptive sizing.',
    alphaThreshold: 'Pixels at or below this source opacity do not produce particles.',
    releaseRandomness: 'Blends the selected release pattern with a fully random order.',
    duration: 'Base lifetime of the particle animation. Longer values make the effect feel slower.',
    stagger: 'Maximum spread between the first and last particle start times.',
    fadeStart: 'Point in each particle lifetime at which fading begins.',
    layoutRelease: 'Share of particles released before the surrounding layout moves.',
    horizontalDrift: 'Adds random sideways variation so particle paths do not look parallel.',
    horizontalMin: 'Smallest horizontal travel. Negative values move particles to the left.',
    horizontalMax: 'Largest horizontal travel. Positive values move particles to the right.',
    verticalMin: 'Smallest vertical travel. Negative values move particles upward.',
    verticalMax: 'Largest vertical travel. Positive values move particles downward.',
    convergence: 'Pulls particles toward the element centre. Zero keeps their paths independent.',
    swirl: 'Sets the amplitude of the vertical wave along each particle path.',
    waveTurns: 'Number of vertical oscillations along each particle path.',
    endScale: 'Particle size at the end of removal, relative to its starting size.',
    rotationMin: 'Smallest detached-particle rotation in degrees.',
    rotationMax: 'Largest detached-particle rotation in degrees.',
    soundSource: 'Bundled audio or a local file.',
    soundReverse: 'Reverses the selected recording without requiring a second audio file.',
    soundVolume: '0–100%.',
    soundPlaybackRate: 'Speed and pitch.',
    soundDelay: 'Pause before playback.',
    soundFadeDuration: 'Fade in and out.',
  },
  ru: {
    curve: 'Меняет ускорение и затухание частиц, но не их траекторию.',
    release: 'Определяет, какая часть элемента начнёт распадаться первой.',
    particleSize: 'Минимальная сторона частицы в CSS-пикселях. Ноль включает автоматический размер.',
    alphaThreshold: 'Пиксели с такой или меньшей непрозрачностью не создают частицы.',
    releaseRandomness: 'Смешивает выбранный порядок распада с полностью случайным.',
    duration: 'Базовое время жизни анимации частиц. Чем больше значение, тем медленнее эффект.',
    stagger: 'Разница во времени запуска частиц. При нуле все частицы стартуют одновременно.',
    fadeStart: 'Момент внутри времени жизни частицы, когда начинается затухание.',
    layoutRelease: 'Доля вылетевших частиц, после которой перестраивается окружающая раскладка.',
    horizontalDrift: 'Добавляет случайное движение в стороны, чтобы частицы летели естественнее.',
    horizontalMin: 'Минимальный путь по горизонтали. Отрицательное значение направляет частицы влево.',
    horizontalMax: 'Максимальный путь по горизонтали. Положительное значение направляет частицы вправо.',
    verticalMin: 'Минимальный путь по вертикали. Отрицательное значение направляет частицы вверх.',
    verticalMax: 'Максимальный путь по вертикали. Положительное значение направляет частицы вниз.',
    convergence: 'Насколько сильно частицы тянутся к центру элемента. При нуле притяжения нет.',
    swirl: 'Насколько сильно частицы колеблются во время движения.',
    waveTurns: 'Количество вертикальных колебаний на пути каждой частицы.',
    endScale: 'Размер частицы в конце анимации. 1× — исходный размер.',
    rotationMin: 'Минимальный поворот отделившейся частицы в градусах.',
    rotationMax: 'Максимальный поворот отделившейся частицы в градусах.',
    soundSource: 'Встроенный звук или локальный файл.',
    soundReverse: 'Воспроизводит выбранную запись задом наперёд без второго аудиофайла.',
    soundVolume: 'Уровень 0–100%.',
    soundPlaybackRate: 'Темп и высота тона.',
    soundDelay: 'Пауза перед стартом.',
    soundFadeDuration: 'Нарастание и затухание.',
  },
  zh: {
    curve: '改变粒子的加速和淡出方式，但不改变运动路径。',
    release: '决定元素的哪个区域最先开始消散。',
    particleSize: '粒子边长的最小 CSS 像素值；设为零时自动计算。',
    alphaThreshold: '源像素透明度不高于此值时不会生成粒子。',
    releaseRandomness: '在所选释放模式与完全随机顺序之间进行混合。',
    duration: '粒子动画的基础持续时间，数值越大效果越慢。',
    stagger: '第一批与最后一批粒子开始时间的最大间隔。',
    fadeStart: '每个粒子在自身生命周期中开始淡出的时刻。',
    layoutRelease: '周围布局开始移动前需要释放的粒子比例。',
    horizontalDrift: '加入随机横向偏移，避免粒子路径显得平行。',
    horizontalMin: '最小水平位移，负值使粒子向左移动。',
    horizontalMax: '最大水平位移，正值使粒子向右移动。',
    verticalMin: '最小垂直位移，负值使粒子向上移动。',
    verticalMax: '最大垂直位移，正值使粒子向下移动。',
    convergence: '将粒子拉向元素中心；设为零时路径彼此独立。',
    swirl: '设置粒子路径上垂直波动的幅度。',
    waveTurns: '每个粒子沿路径产生的垂直波动次数。',
    endScale: '移除结束时粒子相对初始大小的比例。',
    rotationMin: '脱离后的粒子最小旋转角度。',
    rotationMax: '脱离后的粒子最大旋转角度。',
    soundSource: '内置音频或本地文件。',
    soundReverse: '反向播放所选录音，无需第二个音频文件。',
    soundVolume: '0%–100%。',
    soundPlaybackRate: '速度和音高。',
    soundDelay: '播放前等待。',
    soundFadeDuration: '淡入和淡出。',
  },
  ko: {
    curve: '파티클의 이동 경로는 유지하면서 가속과 페이드를 바꿉니다.',
    release: '요소의 어느 부분부터 분해가 시작될지 정합니다.',
    particleSize: '파티클 한 변의 최소 CSS 픽셀 크기입니다. 0이면 자동으로 계산합니다.',
    alphaThreshold: '원본 픽셀의 불투명도가 이 값 이하이면 파티클을 만들지 않습니다.',
    releaseRandomness: '선택한 방출 패턴과 완전한 무작위 순서를 혼합합니다.',
    duration: '파티클 애니메이션의 기본 재생 시간입니다. 값이 클수록 느려집니다.',
    stagger: '첫 파티클과 마지막 파티클의 시작 시간 차이를 정합니다.',
    fadeStart: '각 파티클의 수명에서 페이드가 시작되는 지점입니다.',
    layoutRelease: '주변 레이아웃이 움직이기 전에 방출될 파티클의 비율입니다.',
    horizontalDrift: '무작위 가로 편차를 더해 경로가 평행해 보이지 않게 합니다.',
    horizontalMin: '최소 가로 이동 거리입니다. 음수는 왼쪽으로 이동합니다.',
    horizontalMax: '최대 가로 이동 거리입니다. 양수는 오른쪽으로 이동합니다.',
    verticalMin: '최소 세로 이동 거리입니다. 음수는 위로 이동합니다.',
    verticalMax: '최대 세로 이동 거리입니다. 양수는 아래로 이동합니다.',
    convergence: '파티클을 요소 중앙으로 끌어당깁니다. 0이면 경로가 서로 독립적입니다.',
    swirl: '각 파티클 경로의 세로 파동 진폭을 정합니다.',
    waveTurns: '각 파티클이 이동 경로에서 반복하는 세로 진동 횟수입니다.',
    endScale: '삭제가 끝날 때 시작 크기 대비 파티클 크기입니다.',
    rotationMin: '분리된 파티클의 최소 회전 각도입니다.',
    rotationMax: '분리된 파티클의 최대 회전 각도입니다.',
    soundSource: '내장 오디오 또는 로컬 파일.',
    soundReverse: '두 번째 파일 없이 선택한 녹음을 거꾸로 재생합니다.',
    soundVolume: '0%–100%.',
    soundPlaybackRate: '속도와 음높이.',
    soundDelay: '재생 전 대기.',
    soundFadeDuration: '페이드인·아웃.',
  },
} as const;

export const locale = (typeof document === 'undefined' ? 'en' : (document.body.dataset.locale ?? 'en')) as Locale;

export const copy = copies[locale];

export const help = helps[locale];

export const presetNames: Record<BuiltInPreset, string> = {
  dust: 'Dust',
  scatter: 'Scatter',
  vapor: 'Vapor',
  wind: 'Wind',
};

export const presetDescriptions: Record<Locale, Record<BuiltInPreset, string>> = {
  en: {
    dust: 'diagonal trail',
    scatter: 'spreads outward',
    vapor: 'rises and fades',
    wind: 'drifts sideways',
  },
  ru: {
    dust: 'диагональный шлейф',
    scatter: 'разлёт в стороны',
    vapor: 'вверх и растворяется',
    wind: 'сносит вбок',
  },
  zh: { dust: '对角拖尾', scatter: '向四周散开', vapor: '上升并消散', wind: '横向飘移' },
  ko: { dust: '대각선 궤적', scatter: '사방으로 확산', vapor: '상승하며 사라짐', wind: '옆으로 이동' },
};

export const soundOptionLabels: Record<Locale, Record<BuiltInSound, string>> = {
  en: { dust: 'Dust', scatter: 'Scatter', vapor: 'Vapor', wind: 'Wind' },
  ru: { dust: 'Пыль', scatter: 'Импульс', vapor: 'Пар', wind: 'Ветер' },
  zh: { dust: '尘埃', scatter: '冲击', vapor: '气流', wind: '风声' },
  ko: { dust: '먼지', scatter: '충격', vapor: '공기', wind: '바람' },
};

export const curveOptionLabels: Record<Locale, Record<ParticleCurve, string>> = {
  en: {
    settle: 'settle — gentle settling',
    float: 'float — smooth lift',
    burst: 'burst — quick scatter',
    drift: 'drift — steady wind',
  },
  ru: {
    settle: 'settle — плавное оседание',
    float: 'float — мягкий подъём',
    burst: 'burst — резкий разлёт',
    drift: 'drift — плавный снос',
  },
  zh: { settle: 'settle — 轻柔落下', float: 'float — 平滑上升', burst: 'burst — 快速散开', drift: 'drift — 稳定飘移' },
  ko: {
    settle: 'settle — 부드럽게 가라앉음',
    float: 'float — 부드러운 상승',
    burst: 'burst — 빠른 확산',
    drift: 'drift — 일정한 이동',
  },
};

export const releaseOptionLabels: Record<Locale, Record<ParticleRelease, string>> = {
  en: {
    left: 'left — left to right',
    right: 'right — right to left',
    top: 'top — top to bottom',
    bottom: 'bottom — bottom to top',
    center: 'center — centre outward',
    edges: 'edges — edges inward',
    random: 'random — mixed order',
  },
  ru: {
    left: 'left — слева направо',
    right: 'right — справа налево',
    top: 'top — сверху вниз',
    bottom: 'bottom — снизу вверх',
    center: 'center — от центра',
    edges: 'edges — от краёв',
    random: 'random — случайно',
  },
  zh: {
    left: 'left — 从左到右',
    right: 'right — 从右到左',
    top: 'top — 从上到下',
    bottom: 'bottom — 从下到上',
    center: 'center — 从中心向外',
    edges: 'edges — 从边缘向内',
    random: 'random — 随机',
  },
  ko: {
    left: 'left — 왼쪽에서 오른쪽',
    right: 'right — 오른쪽에서 왼쪽',
    top: 'top — 위에서 아래',
    bottom: 'bottom — 아래에서 위',
    center: 'center — 중앙에서 바깥으로',
    edges: 'edges — 가장자리에서 안쪽으로',
    random: 'random — 무작위',
  },
};

export function createRanges(copy: (typeof copies)[Locale], help: (typeof helps)[Locale]): readonly RangeDefinition[] {
  return [
    { key: 'duration', label: copy.duration, min: 200, max: 3000, step: 25, unit: 'ms', description: help.duration },
    { key: 'stagger', label: copy.stagger, min: 0, max: 800, step: 10, unit: 'ms', description: help.stagger },
    { key: 'fadeStart', label: copy.fadeStart, min: 0, max: 1, step: 0.01, unit: '', description: help.fadeStart },
    {
      key: 'layoutRelease',
      label: copy.layoutRelease,
      min: 0,
      max: 1,
      step: 0.01,
      unit: '',
      description: help.layoutRelease,
    },
    {
      key: 'horizontalDrift',
      label: copy.horizontalDrift,
      min: 0,
      max: 240,
      step: 1,
      unit: 'px',
      description: help.horizontalDrift,
    },
    {
      key: 'horizontalMin',
      label: copy.horizontalMin,
      min: -400,
      max: 400,
      step: 1,
      unit: 'px',
      description: help.horizontalMin,
    },
    {
      key: 'horizontalMax',
      label: copy.horizontalMax,
      min: -400,
      max: 400,
      step: 1,
      unit: 'px',
      description: help.horizontalMax,
    },
    {
      key: 'verticalMin',
      label: copy.verticalMin,
      min: -400,
      max: 400,
      step: 1,
      unit: 'px',
      description: help.verticalMin,
    },
    {
      key: 'verticalMax',
      label: copy.verticalMax,
      min: -400,
      max: 400,
      step: 1,
      unit: 'px',
      description: help.verticalMax,
    },
    {
      key: 'convergence',
      label: copy.convergence,
      min: 0,
      max: 1,
      step: 0.05,
      unit: '',
      description: help.convergence,
    },
    { key: 'swirl', label: copy.swirl, min: 0, max: 160, step: 1, unit: 'px', description: help.swirl },
    { key: 'waveTurns', label: copy.waveTurns, min: 0, max: 5, step: 0.05, unit: '×', description: help.waveTurns },
    { key: 'endScale', label: copy.endScale, min: 0.1, max: 2, step: 0.01, unit: '×', description: help.endScale },
    {
      key: 'particleSize',
      label: copy.particleSize,
      min: 0,
      max: 16,
      step: 0.25,
      unit: 'px',
      description: help.particleSize,
    },
    {
      key: 'alphaThreshold',
      label: copy.alphaThreshold,
      min: 0,
      max: 1,
      step: 0.01,
      unit: '',
      description: help.alphaThreshold,
    },
    {
      key: 'releaseRandomness',
      label: copy.releaseRandomness,
      min: 0,
      max: 1,
      step: 0.01,
      unit: '',
      description: help.releaseRandomness,
    },
    {
      key: 'rotationMin',
      label: copy.rotationMin,
      min: -720,
      max: 720,
      step: 1,
      unit: '°',
      description: help.rotationMin,
    },
    {
      key: 'rotationMax',
      label: copy.rotationMax,
      min: -720,
      max: 720,
      step: 1,
      unit: '°',
      description: help.rotationMax,
    },
    {
      key: 'soundVolume',
      label: copy.soundVolume,
      min: 0,
      max: 1,
      step: 0.01,
      unit: '%',
      description: help.soundVolume,
    },
    {
      key: 'soundPlaybackRate',
      label: copy.soundPlaybackRate,
      min: 0.5,
      max: 2,
      step: 0.01,
      unit: '×',
      description: help.soundPlaybackRate,
    },
    { key: 'soundDelay', label: copy.soundDelay, min: 0, max: 500, step: 10, unit: 'ms', description: help.soundDelay },
    {
      key: 'soundFadeDuration',
      label: copy.soundFadeDuration,
      min: 0,
      max: 1,
      step: 0.01,
      unit: 's',
      description: help.soundFadeDuration,
    },
  ];
}

export const ranges = createRanges(copy, help);
